### ISSUE TITLE
Is it possible to have an up to date release on crates.io?

### ISSUE THREAD

**Issue by lu-zero** [seijikun/kmean-rs#1]

**Comment by seijikun** [comment]
I would love to. But the current version depends on https://github.com/rust-lang/packed_simd/pull/259, which has not yet been released to crates.io.

**Comment by seijikun** [comment]
Now that the `packed_simd` library has been revived and a new version pushed to crates.io, I was able to update kmeans.
I just pushed `0.2.0` to crates.io.

**Comment by lu-zero** [comment]
Thank you a lot!
