### ISSUE TITLE
Question: initializing with custom centroids?

### ISSUE THREAD

**Issue by mfigurski80** [seijikun/kmean-rs#7]
As title indicates, I'm looking for a way to insert pre-computed start positions into the kmeans library. I've tried two approaches thus far, using the interfaces present in the library:

1. Setting in `init_done` callback:
  ``` rust
    let config: KMeansConfig<f64> = KMeansConfig::build().init_done(&|init_state| {
          println!("{:?}", init_state);
          (init_state.centroids) = vec![0.0, 0.0, 0.0, 0.0]; // error here
     }).build();
  ```
  Runs into mutability issues: the `init_state` is passed as immutable.
2. Creating custom init function:
  ``` rust
    let kmeans = KMeans::new(data, 20, 1);
    let result = kmeans.kmeans_lloyd(4, 100, |_, state, _| {
      state.centroids = vec![0.0, 0.0, 0.0, 0.0]; 
    }, &KMeansConfig::default());
  ```
This succeeds but throws a series of internal errors, like: "panicked at called `Option::unwrap()` on a `None` value:<unnamed>/home/miko/.cargo/registry/src/index.crates.io-6f17d22bba15001f/kmeans-0.2.1/src/api.rs"

Apologies if I'm just misusing the library or my code is causing this somehow (and thank you for maintaining an optimized rust kmeans!). Do you know if this is supported in the current version of kmeans-rs?

Edit: would you be up for merging a `precomputed` init method that lets you specify a vec of values like this? Can I make a PR for this?

**Comment by seijikun** [comment]
I just released a new version (`v0.11.0`) with your merge request to crates.io.
Thanks!
